export const FETCH_DEVICES_REQUEST = 'FETCH_DEVICES_REQUEST';
export const FETCH_DEVICES_SUCCESS = 'FETCH_DEVICES_SUCCESS';
export const FETCH_SPECIFIC_DEVICE_REQUEST = 'FETCH_SPECIFIC_DEVICE_REQUEST';
export const FETCH_SPECIFIC_DEVICE_SUCCESS = 'FETCH_SPECIFIC_DEVICE_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ADDCOMMENT_REQUEST = 'ADDCOMMENT_REQUEST';
export const ADDCOMMENT_SUCCESS = 'ADDCOMMENT_SUCCESS';
